import os

# SET YOUR GEMINI API KEY HERE
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "AIzaSyB5OHGs2DgSYeQBE5HmobbFxP4FaMCX40A")
# EMBEDDING CONFIG
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

# CHUNK SIZE
CHUNK_SIZE = 800

# VECTOR STORE PATH
VECTOR_STORE_PATH = "vector_store"
