import os

# SET YOUR GEMINI API KEY HERE
GEMINI_API_KEY = "AIzaSyA_8j6Y0lqAsecdK6ifhrmbogqfAH8IDOs"
# EMBEDDING CONFIG
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

# CHUNK SIZE
CHUNK_SIZE = 800

# VECTOR STORE PATH
VECTOR_STORE_PATH = "vector_store"
